# -*- coding: utf-8 -*-
"""Day_1 Introduction to python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdcCSgrF4KHgkfSp6CYZtdlQwFUfV8bj
"""

# Demo of print
print("Hello world! I am Maverick")

# Demo of print
print("Karan was here")

# Demo of print
print(70-50)
print(10-50)
print(40+10)
print(25*-4)
print(25*4)
print(75/-5)
print(75/5)

# Demo of dynamically typed
a=10
print(type(a))

# Demo of dynamically typed
b="Maverick"
print(type(b))

# Demo of interpreted language (line by line translation)
print("Hello Maverick")
print(10/0)
print("Namaste")

#keywords in python total 35 ie simple language
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

